os:
  - linux
  - osx
language: cpp
compiler:
  - gcc
  - clang
install:
  - ./scripts/travis/install-deps.sh "${TRAVIS_OS_NAME}"
  - ./scripts/travis/install-opentxs.sh "${CXX}" "${TRAVIS_OS_NAME}"
before_script: ./scripts/travis/cppcheck_wrapper.sh ./src
script:
  - mkdir build
  - cd build
  - cmake .. && make -j 2
branches:
  only:
    - master
    - develop
