git:
  depth: 1000
os:
- linux
- osx
language: cpp
compiler:
- gcc
- clang
install:
- ./scripts/travis/install-deps.sh "${TRAVIS_OS_NAME}"
- ./scripts/travis/install-opentxs.sh "0.93.0" "${CXX}" "${TRAVIS_OS_NAME}"
before_script:
- ./scripts/travis/cppcheck_wrapper.sh ./src
- ./scripts/travis/clang-format-checker.sh
script:
- mkdir build
- cd build
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then cmake .. -DCMAKE_PREFIX_PATH="/usr/local/opt/openssl;${TRAVIS_BUILD_DIR}/opentxs" ; else cmake .. -DCMAKE_PREFIX_PATH="${TRAVIS_BUILD_DIR}/opentxs"; fi 
- make -j 2 && make test
- cd ..
before_deploy:
- ./scripts/travis/build_tar.sh "${TRAVIS_OS_NAME}"
deploy:
  provider: s3
  access_key_id: AKIAJGVCHWI7HKTMAKWA
  secret_access_key:
    secure: ceaN6B1b3dDakcyvtjc13MDwUHtyzmS5Sp/zOujPdDZtNHquFL/FOSrsjjJn94GxWsWScoTSEV1bNaojjkTUHMn0iYR1+HGVr6WEE2FYTwwnv4u8byXjvYFEtgQAqyXLRF0Er2QyOskLRAVk/amwBbUbsApRnCJn/gNHDFP7fZ0=
  bucket: monetas-builds
  skip_cleanup: true
  local-dir: s3
  upload-dir: ${TRAVIS_REPO_SLUG}/${TRAVIS_BRANCH}
  on:
    branch: ${TRAVIS_BRANCH}
branches:
  only:
  - master
  - develop
