os:
  - linux
  - osx
language: cpp
compiler:
  - gcc
  - clang
install: ./scripts/travis/install-deps.sh "${TRAVIS_OS_NAME}"
script:
  - ./scripts/travis/cppcheck_wrapper.sh ./src
#  - cmake . && make -j 2
branches:
  only:
    - master
    - develop
